// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ComboController from "controllers/combo_controller"
application.register("combo", ComboController)

import FlashController from "controllers/flash_controller"
application.register("flash", FlashController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ParametersController from "controllers/parameters_controller"
application.register("parameters", ParametersController)

import SearchController from "controllers/search_controller"
application.register("search", SearchController)

import AutoSaveController from "controllers/auto_save_controller"
application.register("auto-save", AutoSaveController)

import ApproveController from "controllers/approve_controller"
application.register("approve", ApproveController)

import TransactionsKeyboardController from "controllers/transactions_keyboard_controller"
application.register("transactions-keyboard", TransactionsKeyboardController)

import CategoryRulesFilterController from "controllers/category_rules_filter_controller"
application.register("category-rules-filter", CategoryRulesFilterController)

import CategoryRulesModalController from "controllers/category_rules_modal_controller"
application.register("category-rules-modal", CategoryRulesModalController)

import ShortcutsHelpController from "controllers/shortcuts_help_controller"
application.register("shortcuts-help", ShortcutsHelpController)

import TransactionValidationController from "controllers/transaction_validation_controller"
application.register("transaction-validation", TransactionValidationController)

import FileDropController from "controllers/file_drop_controller"
application.register("file-drop", FileDropController)

import UploadStatusController from "controllers/upload_status_controller"
application.register("upload-status", UploadStatusController)

import ApproveSimilarController from "controllers/approve_similar_controller"
application.register("approve-similar", ApproveSimilarController)

import SkeletonLoadingController from "controllers/skeleton_loading_controller"
application.register("skeleton-loading", SkeletonLoadingController)