// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import ComboController from "controllers/combo_controller"
application.register("combo", ComboController)

import FlashController from "controllers/flash_controller"
application.register("flash", FlashController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import ParametersController from "controllers/parameters_controller"
application.register("parameters", ParametersController)

import SearchController from "controllers/search_controller"
application.register("search", SearchController)

import AutoSaveController from "controllers/auto_save_controller"
application.register("auto-save", AutoSaveController)

import CategoryRulesFilterController from "controllers/category_rules_filter_controller"
application.register("category-rules-filter", CategoryRulesFilterController)

import CategoryRulesModalController from "controllers/category_rules_modal_controller"
application.register("category-rules-modal", CategoryRulesModalController)